version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend:/usr/src/app"
    ports:
      - 5001:5000
    env_file: .env  # Добавьте эту строку
    environment:
      - FLASK_APP=api/__init__.py
      - FLASK_ENV=development
      - HSDS_ENDPOINT=http://hsds:5101
      - HSDS_BUCKET=wintori
      - HSDS_USERNAME=${HSDS_USERNAME}  # Используем переменную
      - HSDS_PASSWORD=${HSDS_PASSWORD}  # Используем переменную

  hsds:
    image: hdfgroup/hsds:latest
    ports:
      - "5101:5101"
    env_file: .env  # Добавьте эту строку
    environment:
      - HSDS_ENDPOINT=http://0.0.0.0:5101
      - BUCKET_NAME=wintori
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}  # Используем переменную
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}  # Используем переменную
      - AWS_REGION=ru-central1
      - AWS_S3_GATEWAY=https://storage.yandexcloud.net
      - AWS_SIGNATURE_VERSION=4
      - HSDS_ADMIN_USERNAME=admin
      - HSDS_ADMIN_PASSWORD=admin
      - HSDS_LOG_LEVEL=DEBUG
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_SERVICE_URL=http://localhost

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80