version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend:/usr/src/app"
    ports:
      - 5001:5000
    env_file: .env  # Добавьте эту строку
    environment:
      - FLASK_APP=api/__init__.py
      - FLASK_ENV=development
      - HSDS_ENDPOINT=http://hsds-sn:5101
      - HSDS_BUCKET=${BUCKET_NAME}
      - HSDS_USERNAME=${HSDS_USERNAME}
      - HSDS_PASSWORD=${HSDS_PASSWORD}

  hsds-head:
    platform: "linux/amd64"
    image: hdfgroup/hsds
    restart: ${RESTART_POLICY}
    mem_limit: ${HEAD_RAM}
    environment:
      - TARGET_SN_COUNT=${SN_CORES}
      - TARGET_DN_COUNT=${DN_CORES}
      - NODE_TYPE=head_node
      - HEAD_PORT=5100
      - HN_PORT=5100
      - AWS_S3_GATEWAY=${AWS_S3_GATEWAY}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - BUCKET_NAME=${BUCKET_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
    ports:
      - "${HEAD_PORT}:5100"
    volumes:
      - ./admin/config/:/config/
    env_file: .env

  hsds-dn:
    platform: "linux/amd64"
    image: hdfgroup/hsds
    restart: ${RESTART_POLICY}
    mem_limit: ${DN_RAM}
    environment:
      - NODE_TYPE=dn
      - DN_PORT=6101
      - DATA_NODE_PORT=6101
      - HEAD_ENDPOINT=http://hsds-head:5100
      - AWS_S3_GATEWAY=${AWS_S3_GATEWAY}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - BUCKET_NAME=${BUCKET_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
    ports:
      - "${DN_PORT}:6101"
    depends_on:
      - hsds-head
    volumes:
      - ./admin/config/:/config/
    links:
      - hsds-head
    env_file: .env

  hsds-sn:
    platform: "linux/amd64"
    image: hdfgroup/hsds
    restart: ${RESTART_POLICY}
    mem_limit: ${SN_RAM}
    environment:
      - NODE_TYPE=sn
      - SN_PORT=5101
      - SERVICE_NODE_PORT=5101
      - HEAD_ENDPOINT=http://hsds-head:5100
      - AWS_S3_GATEWAY=${AWS_S3_GATEWAY}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - BUCKET_NAME=${BUCKET_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
      - HSDS_ENDPOINT=${HSDS_ENDPOINT}
    ports:
      - "${SN_PORT}:5101"
    depends_on:
      - hsds-head
    volumes:
      - ./admin/config/:/config/
    links:
      - hsds-head
    env_file: .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3007:5173
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_SERVICE_URL=http://localhost
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
